
package com.thalesgroup.authzforce.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthzForce", targetNamespace = "http://pdp.thalesgroup.com/", wsdlLocation = "file:/D:/_DEV/boss-workspace/AuthzForce-PDP/WebContent/WEB-INF/wsdl/AuthzForce.wsdl")
public class AuthzForce_Service
    extends Service
{

    private final static URL AUTHZFORCE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.thalesgroup.authzforce.soap.api.AuthzForce_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.thalesgroup.authzforce.soap.api.AuthzForce_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/_DEV/boss-workspace/AuthzForce-PDP/WebContent/WEB-INF/wsdl/AuthzForce.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/_DEV/boss-workspace/AuthzForce-PDP/WebContent/WEB-INF/wsdl/AuthzForce.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHZFORCE_WSDL_LOCATION = url;
    }

    public AuthzForce_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthzForce_Service() {
        super(AUTHZFORCE_WSDL_LOCATION, new QName("http://pdp.thalesgroup.com/", "AuthzForce"));
    }

    /**
     * 
     * @return
     *     returns AuthzForce
     */
    @WebEndpoint(name = "AuthzForceSOAP")
    public AuthzForce getAuthzForceSOAP() {
        return super.getPort(new QName("http://pdp.thalesgroup.com/", "AuthzForceSOAP"), AuthzForce.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthzForce
     */
    @WebEndpoint(name = "AuthzForceSOAP")
    public AuthzForce getAuthzForceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://pdp.thalesgroup.com/", "AuthzForceSOAP"), AuthzForce.class, features);
    }

}
